### PR TITLE
One line to rule them all

### PR DESCRIPTION
**Pull request by tyleryasaka**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [ ] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)
- [x] Submit to the `develop` branch instead of `master`

Note: tests are not passing for me on `develop`, so I'm not worrying about them right now.

### Description:

Accompanying PR for: https://github.com/OriginProtocol/platform/pull/95

See that PR for details.

### CODE REVIEW

**Comment by wanderingstan** [comment]
> - [ ] Ensure all new and existing tests pass

Do we even have any tests on demo-dapp? I don't see any in the `scripts` dir. 

Everything else is looking good so I'm going to go ahead and merge.

**Comment by tyleryasaka** [comment]
@wanderingstan I've never seen any - we should probably get this straightened out. Either update the checklist or at least create a dummy test and make sure the test command is passing.

**Comment by joshfraser** [comment]
Let's update the checklist. Don't think we need additional tests at this stage.

**Comment by tyleryasaka** [comment]
@joshfraser agreed - also I did fix the test script: https://github.com/OriginProtocol/demo-dapp/pull/112

**Pull request merged**
