### PR TITLE
Topic/contract dev

### PR DESCRIPTION
**Pull request by bretfunk**
Topic/contract dev branch for contract updates:

#25 Add features from Zepplin Library
#23 Show Listing Creation Time

Since these are updates to the contracts, users who already have the demo-dapp locally will need to re-run npm install (to install zeppelin-solidity) and delete all of their json files in the build/contracts directory before running migration in truffle develop again otherwise they will receive a TypeError: Cannot read property 'call' of undefined error when they migrate.

### CODE REVIEW

**Comment by bretfunk** [comment]
Thanks.  
- Sorry about the whitespace, that must have been my Vim auto-formatting.  
-  Roger on the timestamp.  I will move the conversion to the component.  Appreciate the feedback.

**Comment by bretfunk** [comment]
Requested changes made:
- undid contract whitespace alterations
- moved timestamp conversion logic from the contract service to component render
- added creator address to listing (issue #31)

**Comment by bretfunk** [comment]
I have added a fix for issue #33.  I also wrote mocha tests for the listing contract functionality.  Since the updates and tests are all contract related I am pushing to this branch.  Let me know if you prefer a different workflow.

**Comment by nick** [comment]
Going to close this as the demo-dapp has undergone some major changes since February and all the contracts now live in origin-js

**Comment by wanderingstan** [comment]
Thanks for the clean up @nick !

**Pull request closed without merging**
