### PR TITLE
Issue #263 - Webpack automated integration with Crowdin

### PR DESCRIPTION
**Pull request by jordajm**
### Checklist:
- [x] Test your work and double check you didn't break anything
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:
- Creates a webpack plugin to auto-compile all messages to a Crowdin-friendly JSON file
- Updates `crowdin.yml` to point to new `all-messages.json` file
- Fixes duplicate message IDs that were caught by new script

### CODE REVIEW

**Comment by wanderingstan** [comment]
Lazy question with me not looking at the code: I'm assuming the crowdin gives us back json files in the same format we gave it to them. In that case, is there a "mirror" de-compilation tool puts the json back into the format the `react-intl` wants?

**Comment by jordajm** [comment]
Good question - I should have made a note in the PR description - I wanted to get this merged and see how the results come back from Crowdin, then figure out an optimal way to transform those files into a `react-intl`-friendly file
https://github.com/OriginProtocol/demo-dapp/pull/267/files#diff-d9e671cbe822479ba8df0f28e7854c52R46

**Comment by jordajm** [comment]
@micahalcorn this PR is the top priority for review out of my currently outstanding PRs when you get time - it will unblock the translators so they can get cranking on translating the DApp.

**Comment by jordajm** [comment]
@micahalcorn most of the changes in this PR are just changing message IDs so they're all unique b/c the new script caught some duplicates. The meat of the changes are in the webpack plugin, which replaces the old .po files and their scripts.

**Pull request merged**
