### PR TITLE
Civic UI Integration

### PR DESCRIPTION
**Pull request by that1guy**
Added `/login` route and login.js component that leverages our `user-registry-service.js` from platform.  Login.js also leverages our `civic-proxy` to get civic's decrypted user data.

Need to talk about moving the logic that sends post request our `civic-proxy` into platform possibly. (https://github.com/OriginProtocol/demo-dapp/pull/96/files#diff-19ef658434688d0684de4f2a9a7943a4R23)

Also, need to talk about how to stand up civic-proxy on a subdomain of originprotocol.com, right now `civic-proxy` is hardcoded as it only runs on localhost. (https://github.com/OriginProtocol/demo-dapp/pull/96/files#diff-19ef658434688d0684de4f2a9a7943a4R23)

### CODE REVIEW

**Comment by wanderingstan** [comment]
> Also, need to talk about how to stand up civic-proxy on a subdomain of originprotocol.com
@ryana : Can we do this on our EC2 instance along with gateway subdomain?

**Comment by wanderingstan** [comment]
@ryana Nevermind: @joshfraser got it up and running! 
image

**Comment by that1guy** [comment]
@joshfraser thanks for deploying! After @wanderingstan accepts this PR we should quickly update [this code](https://github.com/OriginProtocol/demo-dapp/pull/96/files#diff-19ef658434688d0684de4f2a9a7943a4R23) to send the POST request to `https://civic-proxy.originprotocol.com`.

**Comment by wanderingstan** [comment]
@that1guy not sure how this didn't get counted as closed last week. Sorry for the delay.

**Pull request merged**
